### ISSUE TITLE
[Feature Request] Play videos on Backglass and DMD

### ISSUE THREAD

**Issue by Ltek** [vpinball/b2s-backglass#105]
Would be great to be able to run a video for either screen, Backglass or DMD.

Idea is... many tables have nice Backglasses (exact reproductions or originals) .. but as FullDMDs are quickly taking over, having a nice video in the FullDMD area, would be really nice. Either a simple looping video like what Fabouh designs [https://vpuniverse.com/profile/30150-fabouh/?tab=node_filestabprofile_filesTab](url) or a full attract style video with movie clips, etc.

As I work on more tables I'm seeing this feature is missing and since many do not use Popper, B2Sserver is the perfect app to integrate this.

Initial thought is that using a B2S would be the control point that starts the video player if a video exists. The videos would be named the same as the table (like regular B2Ss) and have a descriptor to identify what screen they are for. This makes it easy to add/remove/change videos for the user.

Example...

SwampThing.VPX
SwampThing.B2S
SwampThing.B2S-DMD.MP4
SwampThing.B2S-BG.MP4

**Comment by JockeJarre** [comment]
Hi Ltek, 
appreciate your new table! But I am not with you on this thingy. We do not need even more overbloat in B2S. 

B2S is good at backglasses up the point where no video is involved. For videos we already have a solution: PinUp player.
If some users do not use PinUp Player (the PUP-Pack player, compared to PinUp popper the table front-end ) that's their problem. The only drawback with PinUp * set of tools, they aren't open-source... but @jsm174 actually got that covered soon... at least on linux, hint @jsm174

I have hardly no time to deal with the real "issues" in the B2S ecosystem, and do not need yet another task... especially since its already there.

That said, I would even say that your suggestion is possible with the tools we already have: I am thinking about [vpinballx.starter](https://vpuniverse.com/files/file/17134-vpinballxstarter/)... here you can control what should happen in general or just a specific table is started. I intend to make it even easier in the future...
If you don't mind, I would ask you to close this ticket... any maybe open one on vpinballx.starter instead ;)

**Comment by Ltek** [comment]
You saying you'd rather add video playback to PinballX Starter?

I'm a Popper user and overall like most of it. Its a lot of parts cobbled together and could be better in a lot of ways with minor tweaks (not being open source is very bad for this, and many reasons). Not heard of what @jsm174 is doing?  Hope it works on Windows also.

**Comment by JockeJarre** [comment]
VPinballX.starter is a toolbox for starting tables with the right VPX version, but it also has a feature to start smaller bat files before a table start and after it has quit. This could be used to start whatever a user might come up with.
But of course it means that the end user has to be found of have to do some work by him/herself. It would not be a out of the box kind of thing. Check it out...
Jason has migrated B2S and parts of Pup to standalone which is currently only on *NIX derivatives (Mac, Linux, Android). But of course there are hopes it might come back to the Win world in the end..
