### ISSUE TITLE
b2s tools should not allow to be run as admin

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/b2s-backglass#75]
If the tools are started as admin, they will try to store files in the windows32 folder.
To avoid this to happen, a requester will come up and say, this should not run as admin and then quit.

**Comment by ivo71** [comment]
I'm getting this error on the latest version as well (B2SServer-2.1.1-f5d3989-Release-win-x86.zip)

**Comment by JockeJarre** [comment]
When does it happen?

This is a new "feature", there are many issues coming up because users are using the toolset wrong. Please check why your installation is starting as admin.
The only B2S program, which has to be started as admin, is B2SBackglassServerRegisterApp.exe, the rest should not!

**Comment by ivo71** [comment]
I am using the 2.1.0 release and that works fine.  I have set everything up with the baller installer and Rudy's guide, which everybody recommends. I can't see any files with the property of start as administrator turned on, so I am not sure how to turn it off. After finding out the 2.1.1 version gave that error, I simply copied 2.1.0 over it again and started the register app and clicked yes to both questions. Now the error is gone. When I copy and register 2.1.1 over the 2.1.0 version, the error is back again.

**Comment by JockeJarre** [comment]
Thanks for the confirmation. So you mean it is while running the register app, you get this error?
I will check how we can fix that!

**Comment by JockeJarre** [comment]
I was trying here with the same B2SServer-2.1.1-fefecf7-Release-win version, but I do not get this coming up.
Can you please describe what you do with screenshots more exact?

**Comment by ivo71** [comment]
1. I am on 2.1.0 and all works fine
2. I copy the contents of the zip of the latest version and overwrite the files in the tables directory.
3. I start B2SBackglassServerRegisterApp.exe and click Yes, OK, Yes to answer the registering overwrite questions.
4. I start a table or double click a b2s file and immediately a pop up appears with the error as shown in the photo (You should not start this as administrator).

When I do the same steps by copying 2.1.0 files over the 2.1.1 files and register them, the problem is gone and everything works fine.

I also tried the version you mentioned (B2SServer-2.1.1-fefecf7-Release-win) and it still has the same error.
![B2S-error](https://github.com/vpinball/b2s-backglass/assets/40582364/6c2cdfd0-5157-4246-a1c1-b170371148e7)

**Comment by JockeJarre** [comment]
thanks for the info! I will check this.

So when running the table through VPX, this isn't a problem, only when you double click the backglass?

**Comment by ivo71** [comment]
No, that's incorrect. With the 2.1.1 version it happens when starting a vpx and also when starting a b2s itself. It doesn't happen at all when using the 2.1.0 release.


-------- Original message --------
From: Jarr3 ***@***.***>
Date: 11/01/24 07:53 (GMT+12:00)
To: vpinball/b2s-backglass ***@***.***>
Cc: ivo71 ***@***.***>, Comment ***@***.***>
Subject: Re: [vpinball/b2s-backglass] b2s tools should not allow to be run as admin (Issue #75)


thanks for the info! I will check this.

So when running the table through VPX, this isn't a problem, only when you double click the backglass?

**Comment by JockeJarre** [comment]
Ok, cause I trying to get more info, when it happens, and this was what you were describing...

Can you please also try double clicking the B2S_ScreenResIdentifier.exe, if you get the same problem here? And if yes, try the 2.1.0 version, if it is able to read and write the screenres.txt correctly.

thanks for the support

**Comment by ivo71** [comment]
in 2.1. I tried to start  B2S_ScreenResIdentifier.exe and it works, but the screens were a bit messy (1st photo).
Then I installed 2.1.1 again and it gave the same administrator error as mentioned in previous messages (I could now not start it).
Then I installed 2.1.0 again and I could start B2S_ScreenResIdentifier.exe again without the error, but the screens were now small and on 1 screen (2nd photo)
![1a](https://github.com/vpinball/b2s-backglass/assets/40582364/84fccd19-91ec-4140-bfc9-08bb6e554f49)

![1b](https://github.com/vpinball/b2s-backglass/assets/40582364/19281e80-62f6-4c9d-8149-ecb152546c1a)

**Comment by ivo71** [comment]
Note, I had my screen at 200% when I started the file, which may have caused the messy layout.

**Comment by JockeJarre** [comment]
Yes, you cannot switch back and fourth between different scaling, cause your file is saved for the other scaling.

**B2S toolset do "support" other scaling than 100%,** writing correct sizes and so on, **but** I have still not yet understood why the GUI looks like this... _would be nice with an additional .NET dev to support the project..._

**Regarding beeing admin**... the new build check if the executable is run as admin, shows the requester and then quits. It has to be something weird going on, _on your system_. I do not know yet what to check. Once I know, I will come back to you.

For playing, please use the official release for now, and I am happy if you can continue help me test these builds going forward... I'll report when there is anything new to try out.

**Comment by ivo71** [comment]
That's fine. I'm more than happy to help. However, I won't be available for the next two weeks after tomorrow. So I'll get back to you then if needed.


-------- Original message --------
From: Jarr3 ***@***.***>
Date: 11/01/24 20:32 (GMT+12:00)
To: vpinball/b2s-backglass ***@***.***>
Cc: ivo71 ***@***.***>, Comment ***@***.***>
Subject: Re: [vpinball/b2s-backglass] b2s tools should not allow to be run as admin (Issue #75)


Yes, you cannot switch back and fourth between different scaling, cause your file is saved for the other scaling.

B2S toolset do "support" other scaling than 100%, writing correct sizes and so on, but I have still not yet understood why the GUI looks like this... would be nice with an additional .NET dev to support the project...

Regarding beeing admin... the new build check if the executable is run as admin, shows the requester and then quits. It has to be something weird going on, on your system. I do not know yet what to check. Once I know, I will come back to you.

For playing, please use the official release for now, and I am happy if you can continue help me test these builds going forward... I'll report when there is anything new to try out.

**Comment by Mrtr32** [comment]
I think if you have an administrator computer account the b2sserver show the administrator warning and don't start
My test computer are built with Windows 7 x64 since 2011 and with your administrator right change, the b2sserver stopped working

**Comment by JockeJarre** [comment]
> I think if you have an administrator computer account the b2sserver show the administrator warning and don't start My test computer are built with Windows 7 x64 since 2011 and with your administrator right change, the b2sserver stopped working

You can safely use the official release for now. I will remove some of the admin tests soon so you can test it. Will inform you soon!

BUT! The B2S_ScreenResIdentifier, does NOT support being run as admin, because windows then automatically defaults to the windows directory instead of saving the screenres file where you expect it to be. 

So I really think you should try to get rid of the installation where everything is running elevated. I beleive to know that it used to be the suggested solution to run as admin in the past, but that's no longer preferred.

And also remember that Windows 7 support ended about _4 years and 1 week ago_, so there will come a day when the toolset  will have a problem with Windows 7 in general.

**Comment by ivo71** [comment]
Hi,
I'm using Windows 10, not Windows 7 and my Windows 10 is fully updated. Can it be that the problem is caused by having uac turned off?


-------- Original message --------
From: Jarr3 ***@***.***>
Date: 27/01/24 01:34 (GMT+10:00)
To: vpinball/b2s-backglass ***@***.***>
Cc: ivo71 ***@***.***>, Comment ***@***.***>
Subject: Re: [vpinball/b2s-backglass] b2s tools should not allow to be run as admin (Issue #75)


I think if you have an administrator computer account the b2sserver show the administrator warning and don't start My test computer are built with Windows 7 x64 since 2011 and with your administrator right change, the b2sserver stopped working

You can safely use the official release for now. I will remove some of the admin tests soon so you can test it. Will inform you soon!

BUT! The B2S_ScreenResIdentifier, does NOT support being run as admin, because windows then automatically defaults to the windows directory instead of saving the screenres file where you expect it to be.

So I really think you should try to get rid of the installation where everything is running elevated. I beleive to know that it used to be the suggested solution to run as admin in the past, but that's no longer preferred.

And also remember that Windows 7 support ended about 4 years and 1 week ago, so there will come a day when the toolset will have a problem with Windows 7 in general.

**Comment by JockeJarre** [comment]
I do not know if that can be a problem, I have UAC active and do not see this problem.
I will relax the tests, but still it isn't preferable to use admin rights everywhere

**Comment by JockeJarre** [comment]
@ivo71 & @Mrtr32 I have now releaxed the admin check in the latest build. So now you should be able to test. Have fun!

**Comment by Mrtr32** [comment]
Work great!

Thanks!

**Comment by ivo71** [comment]
Works great, thanks! And as you said, I can't start the screen res identifier, but that's okay, I can fill it in manually in the screenres.txt.

While trying old and new versions (before I tried the latest one from yesterday), I suddenly have to set and save all my backglass to show the grill. I used to never have to save the settings to show the grill. Can it be that the standard default setting was changed on my system somehow? And then my question is how I can get it back to how it was 🙂
________________________________

**Comment by JockeJarre** [comment]
Hi, I have relaxed the admin check again in the screen_res_identifier. 

This version just informs that admin should not be used, but does not exit.

**Comment by ivo71** [comment]
Hi, it works perfectly. I can even save the screenres.txt file. So now I don't understand why that warning is even needed. Everything works fine. Thanks for the great work 🙂

________________________________

**Comment by JockeJarre** [comment]
We have seen some reports of people starting screen_res_identifier and getting a message that the file cannot be saved to c:\Windows... this was an attempt to make these problems disappear where they occur (50 cm behind the user's screen).
But maybe this isn't the right way to test... or I will add it as a text in the windows instead of a requester.

This is a interim build which is meant for testing, so thanks for testing!

**Comment by JockeJarre** [comment]
Fixed
