### ISSUE TITLE
DB2S Not lights up at start, but only with PWM modified tables

### ISSUE THREAD

**Issue by JockeJarre** [vpinball/b2s-backglass#81]
This issue was logged on VPinMame here [DB2S Not lights up at start, but only with PWM modified tables](https://github.com/vpinball/pinmame/issues/229).
But as @vbousquet mentioned, it is rather the problem that B2S.Server do not know anything about PWM lights.

It currently compares light values set to "0" and "1", when they now can change between "0" and "255"

There is a setting for VPinMame called SolMask(2) for the output mode:
0 = default
1 = modulated solenoid (exist for some years already)
2 = new mode (all solenoids but also lamps, and value if physic meaning, not smoothed out binary state)

**Comment by joco77** [comment]
Hey! The update solved the problem thank you...now the db2s's lights up.
But the problem is with the new update different tables's ball started stuttering. So something can be wrong with this update by performance side.
Same happening for workeyboy too so its not only my problem. 
When we reinstall an older b2s-backglass version the ballstutter is fixed instantly, so something affecting the performance with this update:
https://github.com/vpinball/b2s-backglass/actions/runs/8085186434
sheltemke

**Comment by JockeJarre** [comment]
It has now been tested to work with the latest changes yesterday in issue #99
